/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 Waylo.gltf --transform
*/
import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Waylo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Path.geometry} material={materials['Chrome Glossy 5']}  position={[0, 0, 353.9]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Path_1.geometry} material={materials['Chrome Glossy 5']}  position={[0, -1, 353.9]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Path_2.geometry}material={materials['Chrome Glossy 5']}  position={[0, -2, 353.9]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Path_3.geometry} material={materials['Chrome Glossy 5']} position={[0, -3, 353.9]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Circle.geometry} material={materials['Chrome Glossy 5']} position={[0, -4, 353.9]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Path_4.geometry} material={materials['Chrome Glossy 5']}  position={[0, -5, 353.9]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>

  )
}

useGLTF.preload('/Waylo-transformed.glb')
