/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 noodle.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/noodle-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Path.geometry} material={materials['Titanium Glossy']} position={[0, 0.01, 0.01]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
    </group>
  )
}

useGLTF.preload('/noodle-transformed.glb')
