/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 Waylo.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Waylo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Path.geometry} material={materials['Chrome Glossy 5']} position={[0, 0.35, 0]} scale={0} />
      <mesh geometry={nodes.Path_1.geometry} material={materials['Chrome Glossy 5']} position={[0, 0.35, 0]} scale={0} />
      <mesh geometry={nodes.Path_2.geometry} material={materials['Chrome Glossy 5']} position={[0, 0.35, 0]} scale={0} />
      <mesh geometry={nodes.Path_3.geometry} material={materials['Chrome Glossy 5']} position={[0, 0.35, 0]} scale={0} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Chrome Glossy 5']} position={[0, 0.35, 0]} scale={0} />
      <mesh geometry={nodes.Path_4.geometry} material={materials['Chrome Glossy 5']} position={[0, 0.35, 0.01]} scale={0} />
    </group>
  )
}

useGLTF.preload('/Waylo-transformed.glb')
